# .github/workflows/deploy.yml
name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.19.0'

      - name: Install dependencies with Yarn
        run: yarn install
          
      - name: Build with Vite
        run: yarn build

      - name: Configure Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.ACTIONS }}@github.com/kylelawrence/chortle.git
          
      - name: Clean docs folder
        run: rm -rf docs/*

      - name: Commit docs folder
        run: |
          git add docs
          git diff --cached --quiet || git commit -m "Deploy to GitHub Pages"
          git push
